# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='edit_date_in_token',
            field=models.CharField(default='None', max_length=35),
        ),
    ]
