# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_auto_20171125_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(max_length=400),
        ),
    ]
